name: ci

on:
  push:
    branches:
      - "main"

jobs:
  terraform:
    name: "Provisioning"
    runs-on: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: |
          rm -rf .terraform
          terraform init
      working-directory: "./Terraform"

    

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: "./Terraform"

